# Generated by Django 4.2 on 2024-03-22 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0004_message_owner'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mailing',
            options={'ordering': ('status',), 'permissions': [('set_is_active', 'Изменить активность рассылки')], 'verbose_name': 'Рассылка', 'verbose_name_plural': 'Рассылки'},
        ),
    ]
