# Generated by Django 4.2 on 2024-03-22 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('content', models.TextField(verbose_name='Содержимое статьи')),
                ('image', models.ImageField(blank=True, null=True, upload_to='blog/', verbose_name='Изображение')),
                ('views_count', models.IntegerField(default=0, verbose_name='Просмотры')),
                ('publication_date', models.DateField(auto_now=True, verbose_name='Дата публикации')),
            ],
            options={
                'verbose_name': '',
                'verbose_name_plural': '',
                'ordering': ('publication_date',),
            },
        ),
    ]
